# Generated by Django 3.2.19 on 2023-08-06 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ist_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
