# Generated by Django 3.2.19 on 2023-08-06 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ist_app', '0002_photo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='compound',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
