# Generated by Django 3.2.19 on 2023-08-06 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ist_app', '0003_auto_20230806_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='compound',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photo',
            name='name',
            field=models.CharField(default=True, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photo',
            name='price',
            field=models.IntegerField(default=True),
            preserve_default=False,
        ),
    ]
