# Generated by Django 3.2.19 on 2023-08-07 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ist_app', '0004_auto_20230806_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='compound',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
