# Generated by Django 3.2.19 on 2023-08-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ist_app', '0005_alter_photo_compound'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='compound',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
