# Generated by Django 3.2.19 on 2023-08-18 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ist_app', '0008_rename_photo_post_photo_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='photo_id',
        ),
    ]
